---
- name: Clean the bench directory
  file:
    path: "{{ bench_dir }}"
    state: absent
  tags: run

- name: Create the bench dir
  file:
    path: "{{ bench_dir }}"
    state: directory
  tags: run

- name: Copy the bench application
  copy:
    src: flamestream-benchmark-1.0-SNAPSHOT-uber.jar
    dest: "{{ bench_dir }}/bench.jar"
  tags: run

- name: Copy the configuraion file
  template:
    src: bench.conf.j2
    dest: "{{ bench_dir }}/bench.conf"
  tags: run

- name: Start the flamestream bench
  shell: java -jar {{ bench_dir }}/bench.jar {{ bench_dir }}/bench.conf > {{ bench_dir }}/flamestream_bench.log
  tags: run

- name: Fetch bench logs
  fetch:
    src: "{{ bench_dir }}/flamestream_bench.log"
    dest: flamestream_bench.log
  tags: run
