language: java

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"

install: true

script:
  - mvn clean install -Pqulice --errors --batch-mode
