language: java

sudo: required

addons:
  apt:
    packages:
      - sshpass
      - oracle-java8-installer
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"

install: true

script:
  - mvn -fae --errors --batch-mode clean package

after_failure:
  - ls -al
  - export SSHPASS=$FLAME_PASS
  - sshpass -e scp -v -o stricthostkeychecking=no oom.hprof flamestream@marnikitta.com:~/$TRAVIS_BUILD_ID.hprof
