language: java

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"

install: true

script:
  - mvn clean install -DskipTests -fae --errors --batch-mode
  - cd ./core
  - mvn -fae --errors --batch-mode test
  - cd ../
