language: java
sudo: required
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8

install: true

script:
    - sudo apt update && sudo apt install -y oracle-java8-installer
    - java -version
    - mvn clean install -Pqulice --errors --batch-mode
