language: java

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"

install: true

script:
  - mvn clean install -fae --errors --batch-mode

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t datastreams/worker-application new-core;
    docker push datastreams/worker-application;
    fi

