---
- name: Stopping flink taskmanager
  shell: nohup bash {{ flink_dir }}/bin/taskmanager.sh stop-all
  tags: destroy

- name: Starting flink taskmanager
  shell: nohup bash {{ flink_dir }}/bin/taskmanager.sh start
  tags: bootstrap
