---
- name: Stopping flink taskmanager
  shell: nohup bash {{ flink_dir }}/bin/taskmanager.sh stop-all
  tags:
    - destroy
    - clean

- name: Starting flink taskmanager
  shell: nohup bash {{ flink_dir }}/bin/taskmanager.sh start
  tags:
    - destroy
    - bootstrap
    - clean
