---
- name: Stop the fs worker
  shell: pkill worker.jar || true
  tags: deploy

- name: Clean the fs directory
  file:
    path: "{{ fs_dir }}"
    state: absent
  tags: deploy

- name: Create the fs dir
  file:
    path: "{{ fs_dir }}"
    state: directory
  tags: deploy

- name: Copy the worker application
  copy:
    src: flamestream-benchmarks-1.0-SNAPSHOT-worker.jar
    dest: "{{ fs_dir }}/worker.jar"
  tags: deploy

- name: Copy the configuraion file
  template:
    src: fs.conf.j2
    dest: "{{ fs_dir }}/fs.conf"
  tags: deploy

- name: Start the fs worker
  shell: nohup java -jar {{ fs_dir }}/worker.jar {{ fs_dir }}/fs.conf > /worker.log 2>&1 &
  tags: deploy
