---
- name: Clean the bench directory
  file:
    path: "{{ bench_dir }}"
    state: absent
  tags: clean

- name: Create the bench dir
  file:
    path: "{{ bench_dir }}"
    state: directory
  tags: deliver

- name: Copy wiki
  copy:
    src: wiki.xml
    dest: "{{ bench_dir }}/wiki.xml"
  tags: deliver

- name: Copy the bench application
  copy:
    src: flink-benchmark-1.0-SNAPSHOT-uber.jar
    dest: "{{ bench_dir }}/bench.jar"
  tags: deliver

- name: Copy the configuraion file
  template:
    src: bench.conf.j2
    dest: "{{ bench_dir }}/bench.conf"
  tags: deliver

- name: Start the flink bench
  shell: java -Xmx500m -XX:MaxDirectMemorySize=256m -jar {{ bench_dir }}/bench.jar {{ bench_dir }}/bench.conf > {{ bench_dir }}/flink_bench.log 2>&1
  tags: run

- name: Fetch bench logs
  fetch:
    src: "{{ bench_dir }}/flink_bench.log"
    dest: flink.log
  tags: run
