---
- hosts: all
  roles:
    - { role: common }

- hosts: all
  roles:
    - { role: flink-common }

- hosts: manager
  roles:
    - { role: flink-job-manager }

- hosts: workers
  roles:
    - { role: flink-task-manager }

- hosts: manager
  roles:
    - { role: flink-bench }
